== Introduction to geoCML

geoCML is a Containerized, Multi-paradigm, Lightweight deployment pattern for geographic information systems running locally or in the cloud. geoCML deployments package best-in-class open-source GIS software including QGIS and PostGIS allowing you to quickly go to production. In this topic, you will learn how geoCML deployments work and be able to make an informed decision about whether geoCML is a good choice your needs.

=== How does geoCML work?

geoCML deployments include four containerized microservices: geocml-desktop (the primary user entrypoint), geocml-server (the secondary user entrypoint), geocml-postgres (the primary data store), and geocml-task-scheduler (often abbreviated as gTS). Each service can communicate with each other via an internal network called geocml-network. Once deployed as a geoCML instance, you can begin using geoCML to complete GIS workflows. By design, each geoCML instance should host only one project/dataset. Multiple datasets should be hosted across multiple geoCML instances. Specific documentation on each service is available for your reference.

=== What can geoCML do?

geoCML deployments come out of the box with a variety of features:

- Desktop GIS workflows
- Cloud native server GIS workflows
- Routine database backups
- PostgreSQL/PostGIS database hosting
- Python support for writing custom gTS automation tasks
- Persist information between containerized services via the persistence-layer directory
- Use less space/resources than other enterprise GIS deployments

=== What can geoCML _not_ do out of the box?

geoCML is currently limited in the following areas:

- Integration with ArcGIS proprietary deployments and extensions
- Database version management
- Backup domain values in a database
- Support for storing raster data in geocml-postgres
- MySQL support, SQL Server support, etc (base deployments only support PostgreSQL/PostGIS)

geoCML base deployments are customizable to fit your specific needs. You can customize your services however you'd like! If you would like to contribute to the development of geoCML, you can find the project on GitHub at https://github.com/geocml[github.com/geocml].

=== Quick deployment guide

_Get up and running with geoCML in under 15 minutes!_

geoCML deployments are multi-paradigm, offering a desktop GIS experience and a server GIS experience with a single deployment. You may host your geoCML instance locally or in the cloud, depending on your needs.

Before instantiating a geoCML deployment, you must have https://www.docker.com/[Docker] and https://docs.docker.com/compose/install/[Docker Compose] installed on the machine you want to host geoCML on. You do not need any additional GIS software installed on the machine. Once you have satisfied these conditions, please follow the following steps to deploy your geoCML instance.

. Clone the geoCML source code from https://github.com/geocml/geocml-base-deployment[github.com/geocml/geocml-base-deployment]
. Open a terminal and cd into the source code directory
. Run `docker compose pull` to pull geoCML service images from the project's hosted container registry (optionally, run `docker compose build` to build the images on your machine; this is a requirement if you are modifying your images and have not pushed them to your own registry!)
. Run `docker network create geocml-network`
. Run `docker compose up -d` to bring up the instance

That's it! You can access geoCML Desktop via {deployment host URL}:10000 or geoCML Server portal via {deployment host URL}:80 using a web browser. Further configuration steps for each of these services are discussed in later topics.
